name: RAL
description: Runtime abstraction layer
homepage: https://github.com/DisDis/RAL
author: Igor Demyanov<igor.demyanov@gmail.com>
version: 1.3.0

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
